annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: networking
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 2.11.1
dependencies:
  - name: common
    version: 23.0.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 13.9.20
    repository: oci://tccr.io/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Aplicação de planejamento de produção
home: https://truecharts.org/charts/stable/nginx-proxy-manager
icon: https://www.gstatic.com/webp/gallery/4.webp
keywords:
  - nginx-proxy-manager
  - nginx
  - reverse-proxy
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: Instituto Modal
    email: info@modal.org.br
    url: https://truecharts.org
#MODAL-Usar o mesmo valor da propriedade name no arquivo catalogo
name: powerfab-front
sources:
  - https://nginxproxymanager.com/
  - https://github.com/NginxProxyManager/nginx-proxy-manager
  - https://github.com/truecharts/charts/tree/master/charts/stable/nginx-proxy-manager
  - https://hub.docker.com/r/jc21/nginx-proxy-manager
type: application
version: 10.0.5
